version: 2
jobs:
  build:
    
    working_directory: ~/drift-server

    environment: 
      CI: false

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      - run:
          name: Generate cache key
          command: ./checksum.sh /tmp/checksum.txt

      - restore_cache:
          keys:
          - v-{{ checksum "/tmp/checksum.txt" }}

      - run: mvn --fail-never dependency:go-offline || true

      - save_cache:
          paths:
            - ~/.m2
          key: v-{{ checksum "/tmp/checksum.txt" }}

      - run: mvn clean install

      - run: mvn -f drift-sample/drift-sample-springboot/pom.xml spring-boot:repackage

      - store_artifacts:
          path: drift-sample/drift-sample-springboot/target/drift-sample-springboot-0.0.2-SNAPSHOT.jar
