version: 2
jobs:
  build:
    
    working_directory: ~/drift-server

    environment: 
      CI: false

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      
      - restore_cache:
          keys:
          - v0.0.2-{{ checksum "pom.xml" }}-{{ checksum "drift-core/pom.xml" }}-{{ checksum "drift-server/pom.xml" }}
          - v0.0.2-

      - run: mvn --fail-never dependency:go-offline || true

      - save_cache:
          paths:
            - ~/.m2
          key: v0.0.2-{{ checksum "pom.xml" }}-{{ checksum "drift-core/pom.xml" }}-{{ checksum "drift-server/pom.xml" }}

      - run: mvn clean install surefire-report:report

      - run: mvn -o site
      
      - store_artifacts:
          path: drift-core/target/site
      
      - store_artifacts:
          path: drift-core/target/drift-core-0.0.2-SNAPSHOT.jar
            
      - store_artifacts:
          path: drift-server/target/drift-server-0.0.2-SNAPSHOT.jar
         