micronaut:
    server:
        cors:
            enabled: true
    application:
        name: hello-world
    router:
        static-resources:
            default:
                mapping: /**
                paths: classpath:static
